apiVersion: v1
kind: Service
metadata:
  name: springbootsvc
  labels:
    name: springboot  
spec:
  type: NodePort
  selector:
    name: springboot
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30032
